### ISSUE TITLE
Record and playback

### ISSUE THREAD

**Issue by nirvdrum** [LukeMathWalker/wiremock-rs#65]
Is record and playback in scope for this project? I'm after something like [VCR](https://github.com/vcr/vcr) for Ruby, where real external requests can be made and recorded. Subsequent tests will load up the previously recorded requests and if a request matches exactly, its response will be returned to the client. If no such request can be found (e.g., the client changed something since the last recording), then a 404 will result.

In Ruby, it's achieved by mocking out the client. I realize this project is a bit different. What I'm proposing is the WireMock server would function as a proxy when recording and disallow external connections when in playback mode.

I'm currently looking at ways to achieve this with WireMock. But, if the tool just fundamentally isn't designed for that, it'd be helpful to know. If I can get it working, I'm happy to contribute it back.

**Comment by LukeMathWalker** [comment]
`wiremock-rs` currently supports request recording (see https://docs.rs/wiremock/0.5.2/wiremock/struct.MockServerBuilder.html#method.disable_request_recording and https://docs.rs/wiremock/0.5.2/wiremock/struct.MockServer.html#method.received_requests) but it does not support what is commonly referred to as "Record & Playback" because it would require persisting state outside of a test run.

It is definitely possible to build the functionality using `wiremock-rs`, but I don't see that landing in the crate itself right now.
A project you might be interested into is `stubrs`, which might fulfill your needs (cc @beltram).

**Comment by beltram** [comment]
Yes that would definitely be a great feature for [stubr](https://github.com/beltram/stubr).  
I planned to implement it sometimes anyway. Recording should be pretty straightforward to implement.  
@nirvdrum let's discuss this in a new issue in [stubr](https://github.com/beltram/stubr) if you want !

**Comment by nirvdrum** [comment]
Thanks. I'll close this out then. I hadn't come across _stubr_ (or _wiremock_ for that matter) before. I'll have to spend some time with each and decide where to go from there.

**Comment by nirvdrum** [comment]
In case anyone comes across this issue, there's now a [tracking issue](https://github.com/beltram/stubr/issues/30) for this functionality in _stubr_.
